apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kongs.c2cloud
spec:
  group: c2cloud
  names:
    kind: Kong
    listKind: KongList
    plural: kongs
    singular: kong
  scope: Namespaced
  version: v1alpha1
