kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kong-operator
rules:
- apiGroups:
  - c2cloud.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kong-operator
subjects:
- kind: ServiceAccount
  name: kong-operator
roleRef:
  kind: Role
  name: kong-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kong-operator